name: Check deployed package

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Release-plz']
    types:
      - completed
    branches:
      - main

jobs:
  check-deployed-package:
    name: Check deployed package
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for package to propagate
        run: sleep 60

      - name: Make run script executable
        run: chmod +x check-deployed-package/run.sh

      - name: Check deployed package
        env:
          LOGDASH_API_KEY: ${{ secrets.LOGDASH_API_KEY }}
        run: ./check-deployed-package/run.sh
